cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-versions"
tap "codeclimate/formulae"
tap "eugenmayer/dockersync"
tap "rs/tap"

brew "libyaml"
brew "ansible"
brew "autoconf"
brew "autojump"
brew "automake"
brew "cmake"
brew "cocoapods"
brew "codeclimate"
brew "consul", restart_service: true
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "envchain"
brew "gdb"
brew "git"
brew "git-flow"
brew "go", link: false
brew "glide"
brew "gnu-sed"
brew "go@1.10"
brew "libtool"
brew "graphviz"
brew "git-extras"
brew "htop"
brew "httpie"
brew "hub"
brew "hugo"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "imagemagick@6", link: true
brew "ios-deploy"
brew "node"
brew "joplin"
brew "jq"
brew "kafkacat"
brew "kubernetes-cli"
brew "kops"
brew "kubernetes-helm"
brew "libksba"
brew "make"
brew "neovim"
brew "nmap"
brew "openssl@1.1"
brew "pdsh"
brew "peco"
brew "pkg-config"
brew "prometheus"
brew "pup"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "sysbench"
brew "telnet"
brew "terraform"
brew "terragrunt"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "unison"
brew "vault"
brew "vegeta"
brew "watch"
brew "wget"
brew "yarn"
brew "rs/tap/jaggr"
brew "rs/tap/jplot"
brew "puma/puma/puma-dev"

cask "appcleaner"
cask "launchrocket"
cask "minikube"
cask "java"
cask "java8"
